# This rule is not used by the project healthcheck-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the check.x-health.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: healthcheck-operator
    app.kubernetes.io/managed-by: kustomize
  name: probe-editor-role
rules:
- apiGroups:
  - check.x-health.io
  resources:
  - probes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - check.x-health.io
  resources:
  - probes/status
  verbs:
  - get
