# This rule is not used by the project healthcheck-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over check.x-health.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: healthcheck-operator
    app.kubernetes.io/managed-by: kustomize
  name: probe-admin-role
rules:
- apiGroups:
  - check.x-health.io
  resources:
  - probes
  verbs:
  - '*'
- apiGroups:
  - check.x-health.io
  resources:
  - probes/status
  verbs:
  - get
